version: '3.2'

services:
    app:
        container_name: express
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - ./:/usr/src/app
        ports:
            - '5000:5000'
        env_file: ./.env
        environment:
            NODE_ENV: production
        depends_on:
            - postgres

    postgres:
        container_name: postgres
        image: postgres:${POSTGRES_VERSION:-12}
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
            - './postgres-assets/init.sql:/docker-entrypoint-initdb.d/init.sql'
        ports:
            - '5432:5432'
        restart: unless-stopped

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@example.com}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
            PG_DATABASE: postgres
            PG_USER: ${POSTGRES_USER:-postgres}
            PG_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
        volumes:
            - pgadmin:/root/.pgadmin
            - './postgres-assets/servers.json:/pgadmin4/servers.json'
        ports:
            - '${PGADMIN_PORT:-5050}:80'
        restart: unless-stopped

    express-dev:
        image: node:lts-buster-slim
        container_name: express-dev
        volumes:
            - type: bind
              source: ./
              target: /app
            - type: volume
              source: nodemodules
              target: /app/node_modules
              volume:
                  nocopy: true
        working_dir: /app
        command: npm run dev
        ports:
            - '5000:5000'
        environment:
            - NODE_ENV=development
            - PORT=5000
        depends_on:
            - postgres

volumes:
    postgres:
    pgadmin:
    nodemodules:
